name: publish

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotNET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build
      run: |
        dotnet build -c Release
    - name: Pack
      run: |
        dotnet pack --no-build -c Release -o out NewLife.Core\NewLife.Core.csproj
        dotnet pack --no-build -c Release -o out NewLife.Security\NewLife.Security.csproj

    - name: Publish
      run: |
        dotnet nuget push .\out\*.nupkg --skip-duplicate --source https://nuget.pkg.github.com/NewLifeX/index.json --api-key ${{ github.token }}
        dotnet nuget push .\out\*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nugetKey }}
